language: node_js
node_js:
  - "11"
dist: bionic
install: "npm install"
script: "sh -e run_tests.sh"
notifications:
  email: false
  irc:
    channels: "chat.freenode.net#glowing-bear"
    use_notice: true
    skip_join: true
    on_success: never
    on_failure: always
sudo: false
